GET http://localhost:8083/api/courses

###
GET http://localhost:8083/api/courses/1

###
POST http://localhost:8083/api/courses
Content-Type: application/json

{
  "name": "Spring Framework",
  "limit": 5

}