GET http://localhost:8083/api/courses

###
GET http://localhost:8083/api/courses/1

###
POST http://localhost:8083/api/courses
Content-Type: application/json

{
  "name": "Spring Framework and Kafka",
  "limit": 5

}

###
POST http://localhost:8083/api/courses
Content-Type: application/json

{
  "name": "Spring Cloud",
  "limit": 5,
  "description": "A képzés célja a fontosabb Spring Cloud projektek bemutatása. Minden projekthez több gyakorlati feladat is tartozik. A tanfolyam csak érintőlegesen foglalkozik architektúrális kérdésekkel, microservice architektúrával, tervezési döntésekkel. A Microservice tervezési minták Spring Clouddal megvalósítva Kubernetes környezetben (JAVAX-SPCL) tanfolyam, mely ezeket a kérdéseket járja körbe egy konkrét microservice alkalmazás megvalósításával."

}

###
POST http://localhost:8083/api/courses/1/enrollments
Content-Type: application/json

{
  "employeeIds": [4, 5, 6]
}

###
GET http://localhost:8083/api/course-documents?word=Kubernetes